- name: Install dependencies
  apt:
    name:
      - proot
      - python3-udatetime
      - restic

- name: Install zfs-restic-uploader
  copy:
    src: zfs-restic-uploader
    dest: /opt/zfs-restic-uploader
    mode: 0755

- name: Create config directory
  file:
    path: /etc/zfs-restic-uploader
    state: directory

- name: Place restic password
  copy:
    content: "{{ zru_restic_repo_password }}"
    dest: /etc/zfs-restic-uploader/restic-password
    mode: 0600

- name: Place env file
  template:
    src: env.j2
    dest: /etc/zfs-restic-uploader/env
    mode: 0600

- name: Create systemd service
  template:
    src: service.j2
    dest: /etc/systemd/system/zfs-restic-uploader.service
    mode: 0644
  notify:
    - Reload systemd configuration

- name: Create systemd timer
  template:
    src: timer.j2
    dest: /etc/systemd/system/zfs-restic-uploader.timer
    mode: 0644
  notify:
    - Reload systemd configuration

- meta: flush_handlers

- name: Enable zfs-restic-uploader timer
  systemd:
    name: zfs-restic-uploader.timer
    enabled: true
